apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: developer-hub
  namespace: backstage
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      configMaps:
      - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        # Disabling TLS verification
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
      secrets:
      - name: rhdh-secrets
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  rawRuntimeConfig:
    backstageConfig: rhdh-custom-config