---
- name: Test some stuff
  hosts: localhost 
  connection: local

  tasks:
    - name: Retrieve root token
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: root-user-personal-token
        namespace: gitlab
      register: r_root_token
      failed_when: r_root_token.resources[0].data.token | length == 0

    - name:
      debug:
        var: r_root_token

    - name: Decode root token
      set_fact:
        root_token: '{{ r_root_token.resources[0].data.token | b64decode }}'
    # need to create a personal access token for RHDH to use git
    - name: Create pat for use by RHDH
      ansible.builtin.uri:
        url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/users/1/personal_access_tokens
        method: POST
        body_format: form-urlencoded
        body:
          name: "rhdh token"
          scopes: "api, read_api, read_user, read_repository, write_repository, sudo, admin_mode"
        headers:
          PRIVATE-TOKEN: '{{ root_token }}'
        validate_certs: false
        status_code: 201
      register: new_pat 


    - name: Set gitlab pat
      set_fact:
        gitlab_pat: '{{ new_pat.json.token }}'