---
# tasks file for configure-gitlab

- name: Pause for 5 minutes waiting for GitLab
  ansible.builtin.pause:
    minutes: 5

- name: Check GitLab Liveness
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/projects
    method: GET
    validate_certs: false
  register: r_liveness
  retries: 60
  delay: 10
  until: r_liveness.status == 200

- name: Generate root user personal token
  shell: |
    POD=$(oc get pod -l app=gitlab -n gitlab --no-headers | awk '{print $1}')
    oc exec $POD -n gitlab -- /bin/sh -c /scripts/create-root-pat.sh
    ROOT_PAT=$(oc exec $POD -n gitlab -- /bin/sh -c "cat /tmp/root.pat")
    oc delete secret root-user-personal-token -n gitlab --ignore-not-found
    oc create secret generic root-user-personal-token --from-literal=token=$ROOT_PAT -n gitlab

- name: Retrieve root token
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: root-user-personal-token
    namespace: gitlab
  register: r_root_token
  failed_when: r_root_token.resources[0].data.token | length == 0

- name:
  debug:
    var: r_root_token

- name: Decode root token
  set_fact:
    root_token: '{{ r_root_token.resources[0].data.token | b64decode }}'

- name: Update application settings
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/application/settings
    method: PUT
    body_format: form-urlencoded
    body:
      import_sources: "git,github,gitea"
      version_check_enabled: "false"
      allow_local_requests_from_web_hooks_and_services: "true"
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 200

- name: List users and check if already configured
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/users?username=user1
    method: GET
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 200
  register: r_existingusers

- name: debug pre existing users
  debug:
    var: r_existingusers

- name: Create users
  when: r_existingusers.json | length ==0
  ignore_errors: true
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/users
    method: POST
    body_format: form-urlencoded
    body:
      admin: false
      email: "{{ item }}@demo.redhat.com"
      public_email: "{{ item }}@demo.redhat.com"
      skip_confirmation: true
      username: "{{ item }}"
      password: Developerhub123!
      name: "{{ item }} GitLab"
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: r_user
  loop:
    - user1
    - user2
    - user3
    - user4
    - user5

- name: List users
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/users?per_page=100
    method: GET
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 200
  register: r_users

- name: List groups
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/groups?per_page=100
    method: GET
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 200
  register: r_existing_groups

- name: Create group
  when: r_existing_groups.json | length == 0
  ignore_errors: true
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/groups
    method: POST
    body_format: form-urlencoded
    body:
      name: rhdh
      path: rhdh
      visibility: public
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: r_group

- name: Import repository to group
  when: r_existing_groups.json | length == 0
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/projects
    method: POST
    body_format: form-urlencoded
    body:
      name: '{{ item.name }}'
      import_url: '{{ item.url }}'
      visibility: public
      namespace_id: '{{ r_group.json.id }}'
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  retries: 100
  delay: 5
  register: r_import
  until: r_import.status == 201
  loop:
    - name: rh1-software-templates
      url: https://github.com/redhat-gpe/rh1-rhdh-software-templates.git

- name: Add user to group
  when: r_existing_groups.json | length == 0 and item.username.startswith('user')
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/groups/{{ r_group.json.id }}/members
    method: POST
    body_format: form-urlencoded
    body:
      user_id: '{{ item.id }}'
      access_level: 50
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: r_group_user
  retries: 100
  delay: 5
  until: r_group_user.status == 201
  loop: '{{ r_users.json }}'

- name: Create group
  when: r_existing_groups.json | length == 0
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/groups
    method: POST
    body_format: form-urlencoded
    body:
      name: gitops
      path: gitops
      visibility: public
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: r_group
  retries: 100
  delay: 5
  until: r_group.status == 201

- name: Import repository to group
  when: r_existing_groups.json | length == 0
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/projects
    method: POST
    body_format: form-urlencoded
    body:
      name: '{{ item.name }}'
      import_url: '{{ item.url }}'
      visibility: public
      namespace_id: '{{ r_group.json.id }}'
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  retries: 100
  delay: 5
  register: r_import
  until: r_import.status == 201
  loop:
    - name: janus-idp-gitops
      url: https://github.com/redhat-gpe/janus-idp-gitops.git

- name: Add user to group
  when: r_existing_groups.json | length == 0 and item.username.startswith('user')
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/groups/{{ r_group.json.id }}/members
    method: POST
    body_format: form-urlencoded
    body:
      user_id: '{{ item.id }}'
      access_level: 50
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: r_group_user
  retries: 100
  delay: 5
  until: r_group_user.status == 201
  loop: '{{ r_users.json }}'

- name: Create keycloak application for oidc
  ansible.builtin.uri:
    url: https://gitlab-gitlab.{{ OCP_BASE }}/api/v4/applications
    method: POST
    body_format: form-urlencoded
    body:
      name: "keycloak"
      redirect_uri: "https://keycloak-rhsso.apps.cluster-pwql9.pwql9.sandbox510.opentlc.com/auth/realms/backstage/broker/GitLab/endpoint"
      scopes: "api read_user read_repository write_repository sudo openid profile email"
      confidential: false
    headers:
      PRIVATE-TOKEN: '{{ root_token }}'
    validate_certs: false
    status_code: 201
  register: gitlab_keycloak_app 

- name: Set gitlab application_id
  set_fact:
    gitlab_id: '{{ gitlab_keycloak_app.json.application_id }}'

- name: Set gitlab application secret
  set_fact:
    gitlab_secret: '{{ gitlab_keycloak_app.json.secret }}'