apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: Backstage team
spec:
  type: team
  parent: backstage
  profile:
    # Intentional no displayName for testing
    email: backstage@example.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
spec:
  profile:
    displayName: user1
    email: user1@demo.com
  memberOf: [backstage]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: steve
spec:
  profile:
    displayName: steve
    email: steve@demo.com
  memberOf: [backstage]
---
# This user is added as an example, to make it easier for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
  memberOf: [backstage]
